import { useState } from 'react';
import NoteInput from './components/NoteInput';
import StudyGuide from './components/StudyGuide';
import Flashcards from './components/Flashcards';

import Amplify from 'aws-amplify';
import awsconfig from './aws-exports'; // This file is generated by Amplify

Amplify.configure(awsconfig);

function App() {
  const [studyData, setStudyData] = useState(null);

  return (
    <div className="p-4 max-w-4xl mx-auto">
      <h1 className="text-2xl font-bold mb-4">AI Study Guide Generator</h1>
      <NoteInput onResult={setStudyData} />
      {studyData && (
        <>
          <StudyGuide data={studyData} />
          <Flashcards data={studyData} />
        </>
      )}
    </div>
  );
}

export default App;